alter table public.whatsapp_sessions
  drop constraint if exists whatsapp_sessions_stage_check;

alter table public.whatsapp_sessions
  add constraint whatsapp_sessions_stage_check
  check (
    stage in (
      'idle',
      'choose_vacancy',
      'choose_action',
      'ask_first_name',
      'ask_last_name',
      'ask_email',
      'ask_hours_per_week',
      'ask_age',
      'ask_country',
      'done'
    )
  );

create table if not exists public.whatsapp_applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  wa_id text not null,
  phone_number text not null,
  vacancy text,
  vacancy_label text,
  first_name text,
  last_name text,
  email text,
  hours_per_week int,
  age int,
  country text,
  source text not null default 'whatsapp',
  raw_answers jsonb not null default '{}'::jsonb
);

alter table public.whatsapp_applications
  add column if not exists wa_id text,
  add column if not exists phone_number text,
  add column if not exists vacancy text,
  add column if not exists vacancy_label text,
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists email text,
  add column if not exists hours_per_week int,
  add column if not exists age int,
  add column if not exists country text,
  add column if not exists source text not null default 'whatsapp',
  add column if not exists raw_answers jsonb not null default '{}'::jsonb;

create index if not exists whatsapp_applications_wa_id_idx
  on public.whatsapp_applications (wa_id);

